### ISSUE TITLE
panic under go 1.3.3

### ISSUE THREAD

**Issue by holys** [mvdan/interfacer#14] opened 2015-12-23 11:20 UTC
```
$ interfacer ./...
zsh: correct './...' to './..' [nyae]? n
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ee77]

goroutine 16 [running]:
runtime.panic(0x2582c0, 0x3e22e4)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/mvdan/interfacer.orderedPkgs(0xc208058040, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/holys/code/src/github.com/mvdan/interfacer/check.go:105 +0x3b7
github.com/mvdan/interfacer.CheckArgs(0xc20800e010, 0x1, 0x1, 0x456318, 0xc20803a008, 0x2d8e00, 0x0, 0x0)
	/Users/holys/code/src/github.com/mvdan/interfacer/check.go:123 +0x1c5
main.main()
	/Users/holys/code/src/github.com/mvdan/interfacer/cmd/interfacer/main.go:20 +0xaa

goroutine 19 [finalizer wait]:
runtime.park(0x14350, 0x3e58b0, 0x3e4c29)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x3e58b0, 0x3e4c29)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
```

$ go version
go version go1.3.3 darwin/amd64

**Comment by mvdan** [comment] 2015-12-23 11:55
Duplicate of #7.

**Closed by mvdan** 2015-12-23 11:55 UTC
