### ISSUE TITLE
Does not work with Go's Vendoring process

### ISSUE THREAD

**Issue by djui** [mvdan/interfacer#10] opened 2015-12-22 23:02 UTC
When running the tool and using `GO15VENDOREXPERIMENT=1` I get a lot of `could not import xyz` errors.

**Comment by mvdan** [comment] 2015-12-22 23:04
Got a command I can use to reproduce this issue?

**Comment by djui** [comment] 2015-12-22 23:22
```
$ cd /tmp
$ git clone https://github.com/scraperwiki/hanoverd.git
$ cd hanoverd
$ git submodule init --update --recursive
$ interfacer ./...
/tmp/hanoverd/container.go:13:2: could not import github.com/pwaller/barrier (cannot find package "github.com/pwaller/barrier" in any of:
	/usr/local/Cellar/go/1.5.2/libexec/src/github.com/pwaller/barrier (from $GOROOT)
	/Users/uwe/dev/go/src/github.com/pwaller/barrier (from $GOPATH))
```

**Comment by mvdan** [comment] 2015-12-23 00:21
I get the same result, although:

```sh
 % go build .
container.go:13:2: cannot find package "github.com/pwaller/barrier" in any of:
        /usr/lib/go/src/github.com/pwaller/barrier (from $GOROOT)
        /home/mvdan/go/src/github.com/pwaller/barrier (from $GOPATH)
[more errors]
```

Seems like your method is flawed, or simply that vendoring isn't supposed to work this way - if not, `go build` would work.

This is with `GO15VENDOREXPERIMENT=1`, of course.

**Comment by Vektah** [comment] 2015-12-24 01:03
I think the problem with the example above is `$ cd /tmp`, vendored projects still need to be on your GOPATH.

Here is a simpler test case:
```
# go get github.com/vektah/simple-vendor
# cd $GOPATH/src/github.com/vektah/simple-vendor
# interfacer ./...                              
main.go:3:8: could not import github.com/vektah/dep (cannot find package "github.com/vektah/dep" in any of:
        /opt/go/src/github.com/vektah/dep (from $GOROOT)
        /home/adam/projects/99designs/go/src/github.com/vektah/dep (from $GOPATH))
```

**Comment by mvdan** [comment] 2015-12-24 11:25
Thanks for the example, @Vektah. I can indeed reproduce the issue.

**Comment by djui** [comment] 2015-12-24 11:28
Sorry, yes, I just quickly wrote down the example without thinking not having symlinked/checked out to my _GOPATH_.

**Comment by mvdan** [comment] 2015-12-24 11:49
After some digging, this is what I found.

First, I assumed this was working since vendoring support was just added to `go/loader`:

https://github.com/golang/tools/commit/d6e83e534da905609e21e4086a0fbaed33f88d07

But as it turns out, it is forcefully disabled on 1.5:

https://github.com/golang/tools/blob/d6e83e534da905609e21e4086a0fbaed33f88d07/go/loader/loader.go#L466

Which resolves correctly on 1.6, but always to 0 on 1.5:

https://github.com/golang/tools/blob/d6e83e534da905609e21e4086a0fbaed33f88d07/go/buildutil/buildutil_go15.go
https://github.com/golang/tools/blob/d6e83e534da905609e21e4086a0fbaed33f88d07/go/buildutil/buildutil_go16.go

So we can't really fix this from our side. I think this should be fixed in `go/loader`, but this seems done on purpose for some reason. Maybe it cannot be fixed there?

Paging @adonovan

**Comment by mvdan** [comment] 2015-12-24 11:50
Just to confirm, I just manually modified the `go/loader` source to use a value that would definitely enable `AllowVendor`, such as `63`, and it indeed works on Go 1.5.2:

```
 % GO15VENDOREXPERIMENT=1 interfacer -v github.com/vektah/simple-vendor
github.com/vektah/simple-vendor
```

**Comment by mvdan** [comment] 2015-12-31 09:05
Maybe I wanted to ping @alandonovan instead - looks like the other is his personal account.

**Comment by adonovan** [comment] 2015-12-31 15:24
Thanks for the report.  Glad the fix solves your problem.

**Comment by mvdan** [comment] 2015-12-31 15:32
Well, it's a fix on your end, not on mine :) I don't know whether it's the correct fix either, as it seems to be forced to 0 on 1.5 on purpose - see `go/buildutil/buildutil_go15.go`:

```go
const AllowVendor build.ImportMode = 0
```

**Comment by adonovan** [comment] 2015-12-31 15:40
Sorry, I misunderstood the previous notes.  

The reason the loader's vendoring feature is disabled in pre-1.6 builds is that the necessary support (AllowVendor) was only added to the standard library's `go/build` package in 1.6, so there's no way it can work with 1.5.x.  So I'm not sure what you mean when you say it "works on Go 1.5.2"; the AllowVendor bit should have no effect.

**Comment by mvdan** [comment] 2015-12-31 15:48
Oh. Changing the bit makes the `could not import` error go away, and the program seems to run fine. So I assumed it was fixed. If you say it won't work either way, then it is probably just hiding the error and making the program malfunction in some way.

Thanks for the explanation! I'll close this issue and add a note to the README saying that vendoring support will be possible once 1.6 lands.

**Closed** 2015-12-31 15:48 UTC
Labels: bug
