### ISSUE TITLE
ignore packages that fail to compile

### ISSUE THREAD

**Issue by vikstrous** [mvdan/interfacer#31] opened 2017-01-26 10:04 UTC
I'm not proud of this, but we have a big repo with a lot of go code and some of it is outdated and hasn't been compiled/tested in a while, so it doesn't compile. It would be nice to have an option in interfacer to ignore packages that fail to compile and keep running on the rest so that we can at least see the results from the ones that do compile. I'm not familiar with go's code analysis tools so I don't know how easy/hard this is.

**Comment by mvdan** [comment] 2017-01-26 10:29
The issue is that the tool loads and typechecks all the supplied packages at once. If it was done package by package, the tool would repeat a lot of work and could get a lot more complicated.

This is also a workaround for something that, like you say, isn't really a problem within the tool.

I suggest that, instead of:

```
interfacer $(go list ./... | grep -v /vendor/)
```

You do something like:

```
for pkg in $(go list ./... | grep -v /vendor/); do
    interfacer $pkg # you can ignore stderr here if you want
done
```

**Comment by mvdan** [comment] 2017-01-27 14:04
I'll take the thumbs up as permission to close this as won't fix.

**Closed by mvdan** 2017-01-27 14:04 UTC
