### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lantins** [mvdan/interfacer#8] opened 2015-12-22 21:07 UTC
This may not be very useful to you, as it's just the report, I've not had time to dig into it yet:

`go version go1.5.1 darwin/amd64`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7f361]

goroutine 1 [running]:
github.com/mvdan/interfacer.orderedPkgs(0xc8200725c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lantins/devel/golang/src/github.com/mvdan/interfacer/check.go:105 +0x321
github.com/mvdan/interfacer.CheckArgs(0xc820070030, 0x1, 0x1, 0x68c6c8, 0xc820086008, 0x0, 0x0, 0x0)
	/Users/lantins/devel/golang/src/github.com/mvdan/interfacer/check.go:123 +0x1c8
main.main()
	/Users/lantins/devel/golang/src/github.com/mvdan/interfacer/cmd/interfacer/main.go:20 +0xa4
```

**Comment by mvdan** [comment] 2015-12-22 22:14
Looks like a duplicate of #7, which was already fixed.

**Closed by mvdan** 2015-12-22 22:14 UTC

**Comment by lantins** [comment] 2015-12-22 23:58
Tested against 01c2de0683b8f009841577959e0f41ed543fef3e and its working :+1:
