### ISSUE TITLE
Panic's on main package

### ISSUE THREAD

**Issue by crackcomm** [mvdan/interfacer#12] opened 2015-12-23 02:04 UTC
```
$ interfacer ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47f2b1]

goroutine 1 [running]:
github.com/mvdan/interfacer.orderedPkgs(0xc820012700, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/mvdan/interfacer/check.go:105 +0x321
github.com/mvdan/interfacer.CheckArgs(0xc82000a3b0, 0x1, 0x1, 0x7f58780906f0, 0xc820034010, 0x0, 0x0, 0x0)
	/go/src/github.com/mvdan/interfacer/check.go:123 +0x1c8
main.main()
	/go/src/github.com/mvdan/interfacer/cmd/interfacer/main.go:20 +0xa4
```

**Comment by mvdan** [comment] 2015-12-23 10:40
Duplicate of #7, already fixed.

**Closed by mvdan** 2015-12-23 10:40 UTC
