### ISSUE TITLE
Recognize embeded interfaces

### ISSUE THREAD

**Issue by nizsheanez** [mvdan/interfacer#26] opened 2016-10-05 13:25 UTC
I have interface:

```
type IBusinessRuleContext interface {
    IRWLocker
    Value(interface{}) interface{}
}
type IRWLocker interface {
    sync.Locker
    RLock()
    RUnlock()
}
```

And when i create some object with type `IBusinessRuleContext` interfacer suggests:
`{MyType} can be sync.Locker`

But `sync.Locker` is embedded to `IRWLocker` and it embedded to biggest interface `IBusinessRuleContext`.

**Comment by mvdan** [comment] 2016-10-05 13:37
Could you provide a Go program/package to reproduce this?

**Comment by nizsheanez** [comment] 2016-10-06 07:42
Here it is:

```
package main

import (
	"sync"
)

type IRule interface {
	sync.Locker
	DoIt()
}

type Rule struct {
	sync.Mutex
}

func (c *Rule) DoIt() {
}

func TestInterface(rule IRule)  {
	rule.Lock()
	defer rule.Unlock()
	//uncomment me and error will disappear
	//rule.DoIt()
}

func main() {
	TestInterface(&Rule{})
}
```

**Comment by mvdan** [comment] 2016-10-28 22:42
Sorry, I fail to see what's wrong. The error it shows when the line is commented is correct, and not showing any error when it is uncommented is also correct.

**Comment by mvdan** [comment] 2016-11-08 21:27
Reping @nizsheanez

**Comment by nizsheanez** [comment] 2016-11-09 04:02
Try to create new project, copy my example code to main.go and run `interfacer` in this package.

With commented line:
```
$ interfacer
test.go:19:21: rule can be sync.Locker
```

Uncommented line - `rule can be sync.Locker` disappear: 
```
$ interfacer
```

**Comment by mvdan** [comment] 2016-11-09 09:37
I already tried. As I said, as far as I can tell this is expected behaviour. I want you to tell me what your logic is here.

**Comment by nizsheanez** [comment] 2016-11-09 15:38
ahh... just now realized what means output:
it means "use sync.Locker instead of IRule in whole program in current code block, because it's good to use smaller interfaces" 

but I read it like: "use sync.Locker instead of IRule in whole program" - and it confused me. 

maybe need to adjust message... or only I reading it so crazy way... 

thank you, @mvdan!

**Comment by mvdan** [comment] 2016-11-09 15:42
If you just read the message it could be confusing, but it gives you an exact position pointing to the parameter. Moreover, the purpose of the tool is explained in the README.

Closing since I don't believe the messages should be changed.

**Closed by mvdan** 2016-11-09 15:42 UTC

**Comment by nizsheanez** [comment] 2016-11-10 04:12
sure, if it's in README - then nothing to do.
